
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 23 14:41:22 GMT-04:30 2010
//----------------------------------------------------

package zinara.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 43;
  public static final int ENDDEF = 22;
  public static final int DIVIDE = 12;
  public static final int POW = 14;
  public static final int LTE = 48;
  public static final int LBRACKET = 28;
  public static final int CHAR = 25;
  public static final int UMINUS = 15;
  public static final int CHAR_V = 6;
  public static final int XOR = 58;
  public static final int INTEGER = 23;
  public static final int LPAREN = 29;
  public static final int SEMI = 8;
  public static final int FOR = 64;
  public static final int MINUS = 10;
  public static final int RPAREN = 32;
  public static final int AND = 54;
  public static final int LT = 46;
  public static final int COPY = 39;
  public static final int LBRACET = 30;
  public static final int RBRACET = 33;
  public static final int OR = 56;
  public static final int IN = 53;
  public static final int SHEQ = 50;
  public static final int GTGT = 45;
  public static final int BOOL = 26;
  public static final int COMMA = 34;
  public static final int SAND = 55;
  public static final int ON = 62;
  public static final int DOUBLEDOT = 35;
  public static final int ENDFOR = 20;
  public static final int PLUS = 9;
  public static final int IF = 59;
  public static final int MAIN = 16;
  public static final int ENDWHILE = 19;
  public static final int EOF = 0;
  public static final int ASIG = 66;
  public static final int NOEQ = 52;
  public static final int RETURN = 37;
  public static final int RBRACKET = 31;
  public static final int INTEGER_V = 2;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int DEEQ = 51;
  public static final int MOD = 13;
  public static final int ENDCYCLE = 21;
  public static final int GTE = 49;
  public static final int TIMES = 11;
  public static final int ENDIF = 18;
  public static final int SOR = 57;
  public static final int READ = 41;
  public static final int WHILE = 60;
  public static final int LTLT = 44;
  public static final int FLOAT = 24;
  public static final int FLOAT_V = 3;
  public static final int END = 17;
  public static final int STRING = 27;
  public static final int DEF = 65;
  public static final int RETURNS = 38;
  public static final int CYCLE = 61;
  public static final int FALSE = 5;
  public static final int GT = 47;
  public static final int STRING_V = 7;
  public static final int VAR = 40;
  public static final int DO = 63;
  public static final int PRINT = 42;
  public static final int IDENTIFIER = 36;
}

